#%RAML 1.0 DataType
type: object
example: !include ../examples/book.json
additionalProperties: false
properties:
  isbn:
    type: string
  title:
    type: string
  subtitle:
    type: string
  author:    
    type: string
  published:
    type: datetime
  publisher:
    type: string
  pages:
    type: number
  description:
    type: string
  website:
    type: string
